### ISSUE TITLE
Fix compile errors with dovecot 2.3.7.2

### ISSUE THREAD

**Issue by jrse** [ceph-dovecot/dovecot-ceph-plugin#267]

**Comment by frederikbosch** [comment]
@jrse This project is very interesting, but I wonder what to expect from it. There have been many commits, but last commit dates February last year. Are you running this in production? What are the chances that it gets more attention in the future? I hope you can share some information, but I am very much aware this is open source.

**Comment by jrse** [comment]
@frederikbosch it is under intense test for almost a year and pretty much in a stable state. So we are currently waiting for additional input to develop it further in the right direction.

**Comment by frederikbosch** [comment]
@jrse That is nice to hear. Would you recommend me running this in production? The version of my current Dovecot installation is 2.3.9. If I understand this issue correctly, I should be running a lower version, right?

**Comment by frederikbosch** [comment]
Sorry, I just found the other branch with the latest activity. I thought this project was nearly dead because the master suggests last work was done on Feb 2019. Apparently, you are still working on it. And that branch also suggests there is a plugin version (0.0.23) compatible with Dovecot version 2.3.x. I guess I can better checkout that branch and then compile. Question if the project is production worthy still remains. I hope you can answer that.
